--   Ryan Rozema
--   Assignment 2
--   CPSC 321
--   September 12 2017

SET sql_mode = STRICT_ALL_TABLES; -- Invalid data values are rejected.

USE rrozema_DB; -- Use my own database for this assignment

-- Tables are in the right order to protect foreign key constraints
DROP TABLE IF EXISTS ShootingStats;
DROP TABLE IF EXISTS PerGameStats;
DROP TABLE IF EXISTS Draft;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Team;
DROP TABLE IF EXISTS College; -- Table with the most foreign key constraints is dropped last

CREATE TABLE College (
        college_id INTEGER NOT 0,
        college_name CHAR(50) NOT 0,

        PRIMARY KEY (college_id)
) ENGINE = InnoDB;

CREATE TABLE Team (
	team_code CHAR(5)  NOT 0,
	team_name VARCHAR(50),

	PRIMARY KEY (team_code, team_name)
) ENGINE = InnoDB;

CREATE TABLE Player (
        player_id INTEGER NOT 0,
        player_name CHAR(50) NOT 0,
        age_drafted INTEGER NOT 0, -- Rounded
        position CHAR(5) NOT 0,
	country CHAR(5) NOT 0,
	college_id INTEGER,
	start_year INTEGER,
	graduate_year INTEGER,
	round_drafted INTEGER,
	pick_number INTEGER,
	team_code CHAR(5),

        PRIMARY KEY (player_id),
	FOREIGN KEY (college_id) REFERENCES College(college_id),
	FOREIGN KEY (team_code) REFERENCES Team(team_code)
) ENGINE = InnoDB;

CREATE TABLE PerGameStats (
	player_id INTEGER NOT 0,
        games_played INTEGER NOT 0,
        minuets_played FLOAT NOT 0,
	points FLOAT NOT 0,
	rebounds FLOAT NOT 0,
	assists FLOAT NOT 0,
	steals FLOAT NOT 0,
	blocks FLOAT NOT 0,

        PRIMARY KEY (player_id)
) ENGINE = InnoDB;

CREATE TABLE ShootingStats (
	player_id INTEGER NOT 0,
        field_goal_pct FLOAT NOT 0,
        two_point_pct FLOAT NOT 0,
        three_point_pct FLOAT,
	free_throw_pct FLOAT NOT 0,

	PRIMARY KEY (player_id)
) ENGINE = InnoDB;

INSERT INTO College VALUES (1,'Any');
INSERT INTO College VALUES (2,'Abilene Christian University');
INSERT INTO College VALUES (3,'Acadia University');
INSERT INTO College VALUES (4,'Adams State College');
INSERT INTO College VALUES (5,'Adelphi University');
INSERT INTO College VALUES (6,'Alabama A&amp;M University');
INSERT INTO College VALUES (7,'Alabama State University');
INSERT INTO College VALUES (8,'Albany State University');
INSERT INTO College VALUES (9,'Albertson College of Idaho');
INSERT INTO College VALUES (10,'Albright College');
INSERT INTO College VALUES (11,'Alcorn State University');
INSERT INTO College VALUES (12,'Alderson-Broaddus College');
INSERT INTO College VALUES (13,'Allan Hancock College');
INSERT INTO College VALUES (14,'Alliance College');
INSERT INTO College VALUES (15,'Alliant International University');
INSERT INTO College VALUES (16,'American International College');
INSERT INTO College VALUES (17,'American University');
INSERT INTO College VALUES (18,'Angelo State University');
INSERT INTO College VALUES (19,'Appalachian State University');
INSERT INTO College VALUES (20,'Arizona State University');
INSERT INTO College VALUES (21,'Arkansas State University');
INSERT INTO College VALUES (22,'Arkansas Tech University');
INSERT INTO College VALUES (23,'Armstrong Atlantic State University');
INSERT INTO College VALUES (24,'Ashland University');
INSERT INTO College VALUES (25,'Assumption College');
INSERT INTO College VALUES (26,'Auburn University');
INSERT INTO College VALUES (27,'Auburn University at Montgomery');
INSERT INTO College VALUES (28,'Augsburg College');
INSERT INTO College VALUES (29,'Augusta State University');
INSERT INTO College VALUES (30,'Augustana College (IL)');
INSERT INTO College VALUES (31,'Augustana College (SD)');
INSERT INTO College VALUES (32,'Aurora University');
INSERT INTO College VALUES (33,'Austin Peay State University');
INSERT INTO College VALUES (34,'Azusa Pacific University');
INSERT INTO College VALUES (35,'Baldwin-Wallace College');
INSERT INTO College VALUES (36,'Ball State University');
INSERT INTO College VALUES (37,'Barber-Scotia College');
INSERT INTO College VALUES (38,'Barton County Community College');
INSERT INTO College VALUES (39,'Bates College');
INSERT INTO College VALUES (40,'Bay College');
INSERT INTO College VALUES (41,'Baylor University');
INSERT INTO College VALUES (42,'Belhaven College');
INSERT INTO College VALUES (43,'Bellarmine University');
INSERT INTO College VALUES (44,'Belmont Abbey College');
INSERT INTO College VALUES (45,'Belmont University');
INSERT INTO College VALUES (46,'Beloit College');
INSERT INTO College VALUES (47,'Benedict College');
INSERT INTO College VALUES (48,'Benedictine College');
INSERT INTO College VALUES (49,'Benedictine University');
INSERT INTO College VALUES (50,'Bentley College');
INSERT INTO College VALUES (51,'Bethel College');
INSERT INTO College VALUES (52,'Bethune-Cookman College');
INSERT INTO College VALUES (53,'Biola University');
INSERT INTO College VALUES (54,'Bishop College');
INSERT INTO College VALUES (55,'Bloomfield College');
INSERT INTO College VALUES (56,'Bloomsburg University of Pennsylvania');
INSERT INTO College VALUES (57,'Boise State University');
INSERT INTO College VALUES (58,'Boston College');
INSERT INTO College VALUES (59,'Boston State University');
INSERT INTO College VALUES (60,'Boston University');
INSERT INTO College VALUES (61,'Bowling Green State University');
INSERT INTO College VALUES (62,'Bradley University');
INSERT INTO College VALUES (63,'Brandeis University');
INSERT INTO College VALUES (64,'Briar Cliff University');
INSERT INTO College VALUES (65,'Bridgewater State College');
INSERT INTO College VALUES (66,'Brigham Young University');
INSERT INTO College VALUES (67,'Brigham Young University Hawaii');
INSERT INTO College VALUES (68,'Brown University');
INSERT INTO College VALUES (69,'Bucknell University');
INSERT INTO College VALUES (70,'Butler County Community College');
INSERT INTO College VALUES (71,'Butler University');
INSERT INTO College VALUES (72,'California Institute of Technology');
INSERT INTO College VALUES (73,'California Polytechnic State University');
INSERT INTO College VALUES (74,'Cal State University, Bakersfield');
INSERT INTO College VALUES (75,'Cal State University, Dominguez Hills');
INSERT INTO College VALUES (76,'Cal State University, Fresno');
INSERT INTO College VALUES (77,'Cal State University, Fullerton');
INSERT INTO College VALUES (78,'Cal State University, Long Beach');
INSERT INTO College VALUES (79,'Cal State University, Los Angeles');
INSERT INTO College VALUES (80,'Cal State University, Northridge');
INSERT INTO College VALUES (81,'Cal State University, Sacramento');
INSERT INTO College VALUES (82,'California University of Pennslyvania');
INSERT INTO College VALUES (83,'Cameron University');
INSERT INTO College VALUES (84,'Campbell University');
INSERT INTO College VALUES (85,'Canisius College');
INSERT INTO College VALUES (86,'Carson-Newman College');
INSERT INTO College VALUES (87,'Carthage College');
INSERT INTO College VALUES (88,'Case Western Reserve University');
INSERT INTO College VALUES (89,'Cawtaba College');
INSERT INTO College VALUES (90,'Centenary College of Louisiana');
INSERT INTO College VALUES (91,'Central Connecticut State University');
INSERT INTO College VALUES (92,'Central Michigan University');
INSERT INTO College VALUES (93,'Central Missouri State University');
INSERT INTO College VALUES (94,'Central State University');
INSERT INTO College VALUES (95,'Central Washington University');
INSERT INTO College VALUES (96,'Chaminade University of Honolulu');
INSERT INTO College VALUES (97,'Chapman University');
INSERT INTO College VALUES (98,'Cheyney University of Pennsylvania');
INSERT INTO College VALUES (99,'Chicago State University');
INSERT INTO College VALUES (100,'Christian Brothers University');
INSERT INTO College VALUES (101,'Christopher Newport University');
INSERT INTO College VALUES (102,'City College of New York');
INSERT INTO College VALUES (103,'Clarion University of Pennsylvania');
INSERT INTO College VALUES (104,'Clark Atlanta University');
INSERT INTO College VALUES (105,'Clark University');
INSERT INTO College VALUES (106,'Clemson University');
INSERT INTO College VALUES (107,'Cleveland State University');
INSERT INTO College VALUES (108,'Coe College');
INSERT INTO College VALUES (109,'Colby College');
INSERT INTO College VALUES (110,'Colgate University');
INSERT INTO College VALUES (111,'College of Charleston');
INSERT INTO College VALUES (112,'College of Santa Fe');
INSERT INTO College VALUES (113,'College of the Holy Cross');
INSERT INTO College VALUES (114,'College of the Sequoias');
INSERT INTO College VALUES (115,'College of William &amp; Mary');
INSERT INTO College VALUES (116,'Colorado State University');
INSERT INTO College VALUES (117,'Columbia University');
INSERT INTO College VALUES (118,'Columbus State University');
INSERT INTO College VALUES (119,'Concord University');
INSERT INTO College VALUES (120,'Cooper Union');
INSERT INTO College VALUES (121,'Coppin State University');
INSERT INTO College VALUES (122,'Cornell College');
INSERT INTO College VALUES (123,'Cornell University');
INSERT INTO College VALUES (124,'Creighton University');
INSERT INTO College VALUES (125,'Dakota Wesleyan University');
INSERT INTO College VALUES (126,'Dartmouth College');
INSERT INTO College VALUES (127,'Davidson College');
INSERT INTO College VALUES (128,'Davis &amp; Elkins College');
INSERT INTO College VALUES (129,'Delaware Valley College');
INSERT INTO College VALUES (130,'Delta State University');
INSERT INTO College VALUES (131,'Denver Junior College');
INSERT INTO College VALUES (132,'DePaul University');
INSERT INTO College VALUES (133,'DePauw University');
INSERT INTO College VALUES (134,'Dickinson College');
INSERT INTO College VALUES (135,'Dillard University');
INSERT INTO College VALUES (136,'Doane College');
INSERT INTO College VALUES (137,'Drake University');
INSERT INTO College VALUES (138,'Drexel University');
INSERT INTO College VALUES (139,'Drury University');
INSERT INTO College VALUES (140,'Duke University');
INSERT INTO College VALUES (141,'Duquesne University');
INSERT INTO College VALUES (142,'East Carolina University');
INSERT INTO College VALUES (143,'East Central University');
INSERT INTO College VALUES (144,'East Oregon University');
INSERT INTO College VALUES (145,'East Tennessee State University');
INSERT INTO College VALUES (146,'East Texas State University');
INSERT INTO College VALUES (147,'Eastern Illinois University');
INSERT INTO College VALUES (148,'Eastern Kentucky University');
INSERT INTO College VALUES (149,'Eastern Michigan University');
INSERT INTO College VALUES (150,'Eastern New Mexico University');
INSERT INTO College VALUES (151,'Eastern Washington University');
INSERT INTO College VALUES (152,'Edinboro University of Pennsylvania');
INSERT INTO College VALUES (153,'Elizabeth City State University');
INSERT INTO College VALUES (154,'Elmhurst College');
INSERT INTO College VALUES (155,'Elon University');
INSERT INTO College VALUES (156,'Emporia State University');
INSERT INTO College VALUES (157,'Erskine College');
INSERT INTO College VALUES (158,'Fairfield University');
INSERT INTO College VALUES (159,'Fairleigh Dickinson University');
INSERT INTO College VALUES (160,'Fairmont State University');
INSERT INTO College VALUES (161,'Fayetteville State University');
INSERT INTO College VALUES (162,'Ferris State University');
INSERT INTO College VALUES (163,'Fisk University');
INSERT INTO College VALUES (164,'Florida A&amp;M');
INSERT INTO College VALUES (165,'Florida International University');
INSERT INTO College VALUES (166,'Florida Southern College');
INSERT INTO College VALUES (167,'Florida State University');
INSERT INTO College VALUES (168,'Fordham University');
INSERT INTO College VALUES (169,'Fort Hays State University');
INSERT INTO College VALUES (170,'Fort Valley State University');
INSERT INTO College VALUES (171,'Framingham State College');
INSERT INTO College VALUES (172,'Franciscan University of Steubenville');
INSERT INTO College VALUES (173,'Franklin &amp; Marshall College');
INSERT INTO College VALUES (174,'Furman University');
INSERT INTO College VALUES (175,'Gannon University');
INSERT INTO College VALUES (176,'Gardner-Webb University');
INSERT INTO College VALUES (177,'George Fox University');
INSERT INTO College VALUES (178,'George Mason University');
INSERT INTO College VALUES (179,'George Washington University');
INSERT INTO College VALUES (180,'Georgetown College');
INSERT INTO College VALUES (181,'Georgetown University');
INSERT INTO College VALUES (182,'Georgia Institute of Technology');
INSERT INTO College VALUES (183,'Georgia Southern University');
INSERT INTO College VALUES (184,'Georgia State University');
INSERT INTO College VALUES (185,'Gonzaga University');
INSERT INTO College VALUES (186,'Graceland University');
INSERT INTO College VALUES (187,'Grambling State University');
INSERT INTO College VALUES (188,'Grand Canyon University');
INSERT INTO College VALUES (189,'Grove City College');
INSERT INTO College VALUES (190,'Guilford College');
INSERT INTO College VALUES (191,'Gustavus Adolphus');
INSERT INTO College VALUES (192,'Hamilton College');
INSERT INTO College VALUES (193,'Hamline University');
INSERT INTO College VALUES (194,'Hampton University');
INSERT INTO College VALUES (195,'Hanover College');
INSERT INTO College VALUES (196,'Hardin-Simmons University');
INSERT INTO College VALUES (197,'Harding University');
INSERT INTO College VALUES (198,'Hartwick College');
INSERT INTO College VALUES (199,'Harvard University');
INSERT INTO College VALUES (200,'Hastings College');
INSERT INTO College VALUES (201,'Henderson State University');
INSERT INTO College VALUES (202,'High Point University');
INSERT INTO College VALUES (203,'Hillsdale College');
INSERT INTO College VALUES (204,'Hillside University');
INSERT INTO College VALUES (205,'Hiram College');
INSERT INTO College VALUES (206,'Hiram Scott College');
INSERT INTO College VALUES (207,'Hofstra University');
INSERT INTO College VALUES (208,'Hope College');
INSERT INTO College VALUES (209,'Houston Baptist University');
INSERT INTO College VALUES (210,'Howard Payne University');
INSERT INTO College VALUES (211,'Howard University');
INSERT INTO College VALUES (212,'Humboldt State University');
INSERT INTO College VALUES (213,'Huntington University');
INSERT INTO College VALUES (214,'Huron University');
INSERT INTO College VALUES (215,'Huston-Tillotson University');
INSERT INTO College VALUES (216,'Hutchinson Community College');
INSERT INTO College VALUES (217,'Idaho State University');
INSERT INTO College VALUES (218,'Illinois State University');
INSERT INTO College VALUES (219,'Illinois Wesleyan University');
INSERT INTO College VALUES (220,'Indian Hills Community College');
INSERT INTO College VALUES (221,'Indiana State University');
INSERT INTO College VALUES (222,'Indiana University');
INSERT INTO College VALUES (223,'Indiana University of Pennsylvania');
INSERT INTO College VALUES (224,'IUPUI');
INSERT INTO College VALUES (225,'Iona College');
INSERT INTO College VALUES (226,'Iowa State University');
INSERT INTO College VALUES (227,'Ithaca College');
INSERT INTO College VALUES (228,'Jackson State University');
INSERT INTO College VALUES (229,'Jacksonville State University');
INSERT INTO College VALUES (230,'Jacksonville University');
INSERT INTO College VALUES (231,'James Madison University');
INSERT INTO College VALUES (232,'John Carroll University');
INSERT INTO College VALUES (233,'Johns Hopkins University');
INSERT INTO College VALUES (234,'Johnson C. Smith University');
INSERT INTO College VALUES (235,'Kansas State University');
INSERT INTO College VALUES (236,'Kansas Wesleyan');
INSERT INTO College VALUES (237,'Kent State University');
INSERT INTO College VALUES (238,'Kentucky State University');
INSERT INTO College VALUES (239,'Kentucky Wesleyan College');
INSERT INTO College VALUES (240,'Kenyon College');
INSERT INTO College VALUES (241,'King''s College');
INSERT INTO College VALUES (242,'La Salle University');
INSERT INTO College VALUES (243,'Lafayette College');
INSERT INTO College VALUES (244,'Lake Superior State University');
INSERT INTO College VALUES (245,'Lakeland College');
INSERT INTO College VALUES (246,'Lamar University');
INSERT INTO College VALUES (247,'Lambath University');
INSERT INTO College VALUES (248,'Lane College');
INSERT INTO College VALUES (249,'Lawrence Technological University');
INSERT INTO College VALUES (250,'Lawrence University');
INSERT INTO College VALUES (251,'Lebanon Valley College');
INSERT INTO College VALUES (252,'Lehigh University');
INSERT INTO College VALUES (253,'LeMoyne College');
INSERT INTO College VALUES (254,'LeMoyne-Owen College');
INSERT INTO College VALUES (255,'Lenoir-Rhyne College');
INSERT INTO College VALUES (256,'Lewis and Clark College');
INSERT INTO College VALUES (257,'Lewis University');
INSERT INTO College VALUES (258,'Liberty University');
INSERT INTO College VALUES (259,'Lincoln University of Missouri');
INSERT INTO College VALUES (260,'Linfield College');
INSERT INTO College VALUES (261,'Lipscomb University');
INSERT INTO College VALUES (262,'LIU');
INSERT INTO College VALUES (263,'LIU, C.W. Post Campus');
INSERT INTO College VALUES (264,'LIU, Southampton Campus');
INSERT INTO College VALUES (265,'Longwood University');
INSERT INTO College VALUES (266,'Loras College');
INSERT INTO College VALUES (267,'Louisiana College');
INSERT INTO College VALUES (268,'Louisiana State University');
INSERT INTO College VALUES (269,'Louisiana Tech University');
INSERT INTO College VALUES (270,'Loyola College in Maryland');
INSERT INTO College VALUES (271,'Loyola Marymount University');
INSERT INTO College VALUES (272,'Loyola University New Orleans');
INSERT INTO College VALUES (273,'Loyola University of Chicago');
INSERT INTO College VALUES (274,'Lycoming College');
INSERT INTO College VALUES (275,'Macalester College');
INSERT INTO College VALUES (276,'Malone College');
INSERT INTO College VALUES (277,'Manchester University');
INSERT INTO College VALUES (278,'Manhattan College');
INSERT INTO College VALUES (279,'Marietta College');
INSERT INTO College VALUES (280,'Marion College');
INSERT INTO College VALUES (281,'Marist College');
INSERT INTO College VALUES (282,'Marquette University');
INSERT INTO College VALUES (283,'Marshall University');
INSERT INTO College VALUES (284,'Marymount College');
INSERT INTO College VALUES (285,'McDaniel College');
INSERT INTO College VALUES (286,'McKendree College');
INSERT INTO College VALUES (287,'McMurry University');
INSERT INTO College VALUES (288,'McNeese State University');
INSERT INTO College VALUES (289,'Mercer University');
INSERT INTO College VALUES (290,'Mercyhurst College');
INSERT INTO College VALUES (291,'Merrimack College');
INSERT INTO College VALUES (292,'Miami University');
INSERT INTO College VALUES (293,'Michigan Lutheran');
INSERT INTO College VALUES (294,'Michigan State University');
INSERT INTO College VALUES (295,'Middle Tennessee State University');
INSERT INTO College VALUES (296,'Midwestern State University');
INSERT INTO College VALUES (297,'Miles College');
INSERT INTO College VALUES (298,'Millersville University of Pennsylvania');
INSERT INTO College VALUES (299,'Milligan College');
INSERT INTO College VALUES (300,'Millikin University');
INSERT INTO College VALUES (301,'Minnesota State University, Mankato');
INSERT INTO College VALUES (302,'Mississippi College');
INSERT INTO College VALUES (303,'Mississippi State University');
INSERT INTO College VALUES (304,'Mississippi Valley State University');
INSERT INTO College VALUES (305,'Missouri Southern State University');
INSERT INTO College VALUES (306,'Missouri State University');
INSERT INTO College VALUES (307,'Missouri Valley College');
INSERT INTO College VALUES (308,'Missouri Western State College');
INSERT INTO College VALUES (309,'Monmouth University');
INSERT INTO College VALUES (310,'Montana State University');
INSERT INTO College VALUES (311,'Montana State University, Billings');
INSERT INTO College VALUES (312,'Moravian College');
INSERT INTO College VALUES (313,'Morehead State University');
INSERT INTO College VALUES (314,'Morehouse College');
INSERT INTO College VALUES (315,'Morgan State University');
INSERT INTO College VALUES (316,'Morningside College');
INSERT INTO College VALUES (317,'Morris Brown College');
INSERT INTO College VALUES (318,'Mount St. Mary''s University');
INSERT INTO College VALUES (319,'Muhlenberg College');
INSERT INTO College VALUES (320,'Murray State University');
INSERT INTO College VALUES (321,'Myers University');
INSERT INTO College VALUES (322,'Nasson College');
INSERT INTO College VALUES (323,'New Jersey City University');
INSERT INTO College VALUES (324,'New Mexico Highlands University');
INSERT INTO College VALUES (325,'New Mexico State University');
INSERT INTO College VALUES (326,'New York Institute of Technology');
INSERT INTO College VALUES (327,'New York University');
INSERT INTO College VALUES (328,'Newberry College');
INSERT INTO College VALUES (329,'Niagara University');
INSERT INTO College VALUES (330,'Nicholls State University');
INSERT INTO College VALUES (331,'Norfolk State University');
INSERT INTO College VALUES (332,'North Carolina A&amp;T');
INSERT INTO College VALUES (333,'North Carolina Central University');
INSERT INTO College VALUES (334,'North Carolina State University');
INSERT INTO College VALUES (335,'North Central College');
INSERT INTO College VALUES (336,'North Dakota State University');
INSERT INTO College VALUES (337,'North Park University');
INSERT INTO College VALUES (338,'Northeast Miss. CC');
INSERT INTO College VALUES (339,'Northeastern Illinois University');
INSERT INTO College VALUES (340,'Northeastern State University');
INSERT INTO College VALUES (341,'Northeastern University');
INSERT INTO College VALUES (342,'Northern Arizona University');
INSERT INTO College VALUES (343,'Northern Illinois University');
INSERT INTO College VALUES (344,'Northern Michigan University');
INSERT INTO College VALUES (345,'Northern State University');
INSERT INTO College VALUES (346,'Northwest Missouri State University');
INSERT INTO College VALUES (347,'Northwestern Okla. State University');
INSERT INTO College VALUES (348,'Northwestern State University');
INSERT INTO College VALUES (349,'Northwestern University');
INSERT INTO College VALUES (350,'Northwood Institute');
INSERT INTO College VALUES (351,'Northwood University');
INSERT INTO College VALUES (352,'Oakland University');
INSERT INTO College VALUES (353,'Oberlin College');
INSERT INTO College VALUES (354,'Occidental College');
INSERT INTO College VALUES (355,'Oglethorpe University');
INSERT INTO College VALUES (356,'Ohio State University');
INSERT INTO College VALUES (357,'Ohio University');
INSERT INTO College VALUES (358,'Ohio Wesleyan University');
INSERT INTO College VALUES (359,'Okaloosa-Walton Community College');
INSERT INTO College VALUES (360,'Oklahoma Baptist University');
INSERT INTO College VALUES (361,'Oklahoma Christian University');
INSERT INTO College VALUES (362,'Oklahoma City University');
INSERT INTO College VALUES (363,'Oklahoma Panhandle State University');
INSERT INTO College VALUES (364,'Oklahoma State University');
INSERT INTO College VALUES (365,'Old Dominion University');
INSERT INTO College VALUES (366,'Oral Roberts University');
INSERT INTO College VALUES (367,'Oregon State University');
INSERT INTO College VALUES (368,'Otterbein College');
INSERT INTO College VALUES (369,'Ouachita Baptist University');
INSERT INTO College VALUES (370,'Pace University');
INSERT INTO College VALUES (371,'Pacific Lutheran University');
INSERT INTO College VALUES (372,'Pacific University');
INSERT INTO College VALUES (373,'Paine College');
INSERT INTO College VALUES (374,'Paul Quinn College');
INSERT INTO College VALUES (375,'Pennsylvania State University');
INSERT INTO College VALUES (376,'Pepperdine University');
INSERT INTO College VALUES (377,'Philadelphia University');
INSERT INTO College VALUES (378,'Phillips University');
INSERT INTO College VALUES (379,'Pikeville College');
INSERT INTO College VALUES (380,'Point Loma Nazarene University');
INSERT INTO College VALUES (381,'Point Park University');
INSERT INTO College VALUES (382,'Polytechnic University');
INSERT INTO College VALUES (383,'Portland State University');
INSERT INTO College VALUES (384,'Prairie View A&amp;M University');
INSERT INTO College VALUES (385,'Pratt Institute');
INSERT INTO College VALUES (386,'Presbyterian College');
INSERT INTO College VALUES (387,'Princeton University');
INSERT INTO College VALUES (388,'Providence College');
INSERT INTO College VALUES (389,'Purdue University');
INSERT INTO College VALUES (390,'Quinnipiac University');
INSERT INTO College VALUES (391,'Randolph-Macon College');
INSERT INTO College VALUES (392,'Regis University');
INSERT INTO College VALUES (393,'Rice University');
INSERT INTO College VALUES (394,'Rider University');
INSERT INTO College VALUES (395,'Ripon College');
INSERT INTO College VALUES (396,'Roanoke College');
INSERT INTO College VALUES (397,'Robert Morris University (PA)');
INSERT INTO College VALUES (398,'Rochester Institute of Technology');
INSERT INTO College VALUES (399,'Rockhurst University');
INSERT INTO College VALUES (400,'Rocky Mountain College');
INSERT INTO College VALUES (401,'Rutgers University');
INSERT INTO College VALUES (402,'Rutgers University-Camden');
INSERT INTO College VALUES (403,'Sacred Heart University');
INSERT INTO College VALUES (404,'Saint Anselm College');
INSERT INTO College VALUES (405,'Saint Augustine''s College');
INSERT INTO College VALUES (406,'Saint Francis University');
INSERT INTO College VALUES (407,'Saint Joseph''s College');
INSERT INTO College VALUES (408,'Saint Joseph''s University');
INSERT INTO College VALUES (409,'Saint Leo University');
INSERT INTO College VALUES (410,'Saint Louis University');
INSERT INTO College VALUES (411,'Saint Mary of the Plains College');
INSERT INTO College VALUES (412,'Saint Mary''s College of California');
INSERT INTO College VALUES (413,'Saint Mary''s University');
INSERT INTO College VALUES (414,'Saint Michael''s College');
INSERT INTO College VALUES (415,'Saint Paul''s College');
INSERT INTO College VALUES (416,'Saint Peter''s College');
INSERT INTO College VALUES (417,'Salem International University');
INSERT INTO College VALUES (418,'Sam Houston State University');
INSERT INTO College VALUES (419,'Samford University');
INSERT INTO College VALUES (420,'San Diego State University');
INSERT INTO College VALUES (421,'San Francisco State University');
INSERT INTO College VALUES (422,'San Jose State University');
INSERT INTO College VALUES (423,'Santa Clara University');
INSERT INTO College VALUES (424,'Savannah State University');
INSERT INTO College VALUES (425,'Seattle Pacific University');
INSERT INTO College VALUES (426,'Seattle University');
INSERT INTO College VALUES (427,'Seton Hall University');
INSERT INTO College VALUES (428,'Seward County Community College');
INSERT INTO College VALUES (429,'Shaw University');
INSERT INTO College VALUES (430,'Shepherd College');
INSERT INTO College VALUES (431,'Siena College');
INSERT INTO College VALUES (432,'Simon Fraser University');
INSERT INTO College VALUES (433,'Sir George Williams University');
INSERT INTO College VALUES (434,'Slippery Rock University (Pa.)');
INSERT INTO College VALUES (435,'South Carolina State University');
INSERT INTO College VALUES (436,'South Dakota State University');
INSERT INTO College VALUES (437,'Southeast Missouri State University');
INSERT INTO College VALUES (438,'Southeastern Illinois College');
INSERT INTO College VALUES (439,'Southeastern Louisiana University');
INSERT INTO College VALUES (440,'SE Okla. State University');
INSERT INTO College VALUES (441,'Southern Illinois University');
INSERT INTO College VALUES (442,'Southern Methodist University');
INSERT INTO College VALUES (443,'Southern Nazarene University');
INSERT INTO College VALUES (444,'Southern New Hampshire University');
INSERT INTO College VALUES (445,'Southern University and A&amp;M College');
INSERT INTO College VALUES (446,'Southern Utah University');
INSERT INTO College VALUES (447,'Southwestern College');
INSERT INTO College VALUES (448,'SW Okla. State University');
INSERT INTO College VALUES (449,'Southwstern University');
INSERT INTO College VALUES (450,'Spring Hill College');
INSERT INTO College VALUES (451,'Springfield College');
INSERT INTO College VALUES (452,'St. Ambrose University');
INSERT INTO College VALUES (453,'St. Bonaventure University');
INSERT INTO College VALUES (454,'St. Cloud State University');
INSERT INTO College VALUES (455,'St. Francis College');
INSERT INTO College VALUES (456,'St. John Fisher College');
INSERT INTO College VALUES (457,'St. John''s University');
INSERT INTO College VALUES (458,'St. Mary''s College of Maryland');
INSERT INTO College VALUES (459,'St. Mary''s University');
INSERT INTO College VALUES (460,'St. Thomas University');
INSERT INTO College VALUES (461,'Stanford University');
INSERT INTO College VALUES (462,'SUNY at Brockport');
INSERT INTO College VALUES (463,'SUNY at Potsdam');
INSERT INTO College VALUES (464,'SUNY College at Buffalo');
INSERT INTO College VALUES (465,'State University of West Georgia');
INSERT INTO College VALUES (466,'Stephen F. Austin State University');
INSERT INTO College VALUES (467,'Stetson University');
INSERT INTO College VALUES (468,'Stonehill College');
INSERT INTO College VALUES (469,'Suffolk University');
INSERT INTO College VALUES (470,'Sul Ross State University');
INSERT INTO College VALUES (471,'Swarthmore College');
INSERT INTO College VALUES (472,'Syracuse University');
INSERT INTO College VALUES (473,'Taylor University');
INSERT INTO College VALUES (474,'Temple University');
INSERT INTO College VALUES (475,'Tennessee State University');
INSERT INTO College VALUES (476,'Tennessee Technological University');
INSERT INTO College VALUES (477,'Tennessee Wesleyan College');
INSERT INTO College VALUES (478,'Texas A&amp;M University');
INSERT INTO College VALUES (479,'Texas A&amp;M University-Kingsville');
INSERT INTO College VALUES (480,'Texas Christian University');
INSERT INTO College VALUES (481,'Texas Southern University');
INSERT INTO College VALUES (482,'Texas State University');
INSERT INTO College VALUES (483,'Texas Tech University');
INSERT INTO College VALUES (484,'Texas Wesleyan University');
INSERT INTO College VALUES (485,'The Citadel');
INSERT INTO College VALUES (486,'Thomas More College');
INSERT INTO College VALUES (487,'Tougaloo College');
INSERT INTO College VALUES (488,'Towson University');
INSERT INTO College VALUES (489,'Transylvania University');
INSERT INTO College VALUES (490,'Trenton State University');
INSERT INTO College VALUES (491,'Trinity University');
INSERT INTO College VALUES (492,'Trinity Valley Community College');
INSERT INTO College VALUES (493,'Truman State University');
INSERT INTO College VALUES (494,'Tufts University');
INSERT INTO College VALUES (495,'Tulane University');
INSERT INTO College VALUES (496,'Tuskegee University');
INSERT INTO College VALUES (497,'Union College');
INSERT INTO College VALUES (498,'Union University');
INSERT INTO College VALUES (499,'United States Air Force Academy');
INSERT INTO College VALUES (500,'United States Military Academy');
INSERT INTO College VALUES (501,'United States Naval Academy');
INSERT INTO College VALUES (502,'University at Buffalo, SUNY');
INSERT INTO College VALUES (503,'University of Akron');
INSERT INTO College VALUES (504,'University of Alabama');
INSERT INTO College VALUES (505,'University of Alabama at Birmingham');
INSERT INTO College VALUES (506,'University of Alabama at Huntsville');
INSERT INTO College VALUES (507,'University of Alaska Anchorage');
INSERT INTO College VALUES (508,'University of Albuquerque');
INSERT INTO College VALUES (509,'University of Arizona');
INSERT INTO College VALUES (510,'University of Arkansas');
INSERT INTO College VALUES (511,'University of Arkansas at Little Rock');
INSERT INTO College VALUES (512,'University of Arkansas at Pine Bluff');
INSERT INTO College VALUES (513,'University of Baltimore');
INSERT INTO College VALUES (514,'University of Bridgeport');
INSERT INTO College VALUES (515,'University of British Columbia');
INSERT INTO College VALUES (516,'University of Calgary');
INSERT INTO College VALUES (517,'University of California');
INSERT INTO College VALUES (518,'University of California, Davis');
INSERT INTO College VALUES (519,'University of California, Irvine');
INSERT INTO College VALUES (520,'University of California Los Angeles');
INSERT INTO College VALUES (521,'University of California, Riverside');
INSERT INTO College VALUES (522,'University of California, San Diego');
INSERT INTO College VALUES (523,'University of California, Santa Barbara');
INSERT INTO College VALUES (524,'University of Central Arkansas');
INSERT INTO College VALUES (525,'University of Central Florida');
INSERT INTO College VALUES (526,'University of Charleston');
INSERT INTO College VALUES (527,'University of Cincinnati');
INSERT INTO College VALUES (528,'University of Colorado');
INSERT INTO College VALUES (529,'University of Connecticut');
INSERT INTO College VALUES (530,'University of Dayton');
INSERT INTO College VALUES (531,'University of Delaware');
INSERT INTO College VALUES (532,'University of Denver');
INSERT INTO College VALUES (533,'University of Detroit Mercy');
INSERT INTO College VALUES (534,'University of Evansville');
INSERT INTO College VALUES (535,'University of Findlay');
INSERT INTO College VALUES (536,'University of Florida');
INSERT INTO College VALUES (537,'University of Georgia');
INSERT INTO College VALUES (538,'University of Great Falls');
INSERT INTO College VALUES (539,'University of Hartford');
INSERT INTO College VALUES (540,'University of Hawaii');
INSERT INTO College VALUES (541,'University of Houston');
INSERT INTO College VALUES (542,'University of Idaho');
INSERT INTO College VALUES (543,'University of Ill. at Chicago');
INSERT INTO College VALUES (544,'University of Ill. at Urbana-Champaign');
INSERT INTO College VALUES (545,'University of Indianapolis');
INSERT INTO College VALUES (546,'University of Iowa');
INSERT INTO College VALUES (547,'University of Kansas');
INSERT INTO College VALUES (548,'University of Kentucky');
INSERT INTO College VALUES (549,'University of La Verne');
INSERT INTO College VALUES (550,'University of Lethbridge');
INSERT INTO College VALUES (551,'University of Louisiana at Lafayette');
INSERT INTO College VALUES (552,'University of Louisiana at Monroe');
INSERT INTO College VALUES (553,'University of Louisville');
INSERT INTO College VALUES (554,'University of Maine');
INSERT INTO College VALUES (555,'University of Maryland');
INSERT INTO College VALUES (556,'University of Maryland Eastern Shore');
INSERT INTO College VALUES (557,'University of Maryland, Baltimore County');
INSERT INTO College VALUES (558,'University of Massachusetts Amherst');
INSERT INTO College VALUES (559,'University of Massachusetts Boston');
INSERT INTO College VALUES (560,'University of Massachusetts Dartmouth');
INSERT INTO College VALUES (561,'University of Massachusetts Lowell');
INSERT INTO College VALUES (562,'University of Memphis');
INSERT INTO College VALUES (563,'University of Miami');
INSERT INTO College VALUES (564,'University of Michigan');
INSERT INTO College VALUES (565,'University of Minnesota');
INSERT INTO College VALUES (566,'University of Minnesota Morris');
INSERT INTO College VALUES (567,'University of Mississippi');
INSERT INTO College VALUES (568,'University of Missouri');
INSERT INTO College VALUES (569,'University of Missouri-Kansas City');
INSERT INTO College VALUES (570,'University of Missouri-Rolla');
INSERT INTO College VALUES (571,'University of Missouri-St. Louis');
INSERT INTO College VALUES (572,'University of Montana');
INSERT INTO College VALUES (573,'University of Montana-Western');
INSERT INTO College VALUES (574,'University of Nebraska');
INSERT INTO College VALUES (575,'University of Nebraska at Kearney');
INSERT INTO College VALUES (576,'University of Nebraska at Omaha');
INSERT INTO College VALUES (577,'University of Nevada, Las Vegas');
INSERT INTO College VALUES (578,'University of Nevada, Reno');
INSERT INTO College VALUES (579,'University of New Hampshire');
INSERT INTO College VALUES (580,'University of New Haven');
INSERT INTO College VALUES (581,'University of New Mexico');
INSERT INTO College VALUES (582,'University of New Orleans');
INSERT INTO College VALUES (583,'University of North Alabama');
INSERT INTO College VALUES (584,'Univ. of North Carolina');
INSERT INTO College VALUES (585,'Univ. of North Carolina at Charlotte');
INSERT INTO College VALUES (586,'Univ. of North Carolina at Pembroke');
INSERT INTO College VALUES (587,'Univ. of North Carolina at Wilmington');
INSERT INTO College VALUES (588,'University of North Dakota');
INSERT INTO College VALUES (589,'University of North Texas');
INSERT INTO College VALUES (590,'University of Northern Iowa');
INSERT INTO College VALUES (591,'University of Notre Dame');
INSERT INTO College VALUES (592,'University of Oklahoma');
INSERT INTO College VALUES (593,'University of Oregon');
INSERT INTO College VALUES (594,'University of Pennsylvania');
INSERT INTO College VALUES (595,'University of Pittsburgh');
INSERT INTO College VALUES (596,'University of Portland');
INSERT INTO College VALUES (597,'University of Puget Sound');
INSERT INTO College VALUES (598,'University of Rhode Island');
INSERT INTO College VALUES (599,'University of Richmond');
INSERT INTO College VALUES (600,'University of Rio Grande');
INSERT INTO College VALUES (601,'University of Rochester');
INSERT INTO College VALUES (602,'University of San Diego');
INSERT INTO College VALUES (603,'University of San Francisco');
INSERT INTO College VALUES (604,'University of Scranton');
INSERT INTO College VALUES (605,'University of South Alabama');
INSERT INTO College VALUES (606,'University of South Carolina');
INSERT INTO College VALUES (607,'University of South Carolina Upstate');
INSERT INTO College VALUES (608,'University of South Dakota');
INSERT INTO College VALUES (609,'University of South Florida');
INSERT INTO College VALUES (610,'University of Southern California');
INSERT INTO College VALUES (611,'University of Southern Colorado');
INSERT INTO College VALUES (612,'University of Southern Indiana');
INSERT INTO College VALUES (613,'University of Southern Mississippi');
INSERT INTO College VALUES (614,'University of St. Thomas');
INSERT INTO College VALUES (615,'University of Tampa');
INSERT INTO College VALUES (616,'University of Tennessee');
INSERT INTO College VALUES (617,'University of Tennessee at Chattanooga');
INSERT INTO College VALUES (618,'University of Tennessee at Martin');
INSERT INTO College VALUES (619,'University of Texas at Arlington');
INSERT INTO College VALUES (620,'University of Texas at Austin');
INSERT INTO College VALUES (621,'University of Texas at El Paso');
INSERT INTO College VALUES (622,'University of Texas at San Antonio');
INSERT INTO College VALUES (623,'University of Texas-Pan American');
INSERT INTO College VALUES (624,'University of the District of Columbia');
INSERT INTO College VALUES (625,'University of the Pacific');
INSERT INTO College VALUES (626,'University of Toledo');
INSERT INTO College VALUES (627,'University of Tulsa');
INSERT INTO College VALUES (628,'University of Utah');
INSERT INTO College VALUES (629,'University of Vermont');
INSERT INTO College VALUES (630,'University of Virginia');
INSERT INTO College VALUES (631,'University of Washington');
INSERT INTO College VALUES (632,'University of West Florida');
INSERT INTO College VALUES (633,'University of Wisconsin');
INSERT INTO College VALUES (634,'University of Wisconsin-Eau Claire');
INSERT INTO College VALUES (635,'University of Wisconsin-Green Bay');
INSERT INTO College VALUES (636,'University of Wisconsin-LaCrosse');
INSERT INTO College VALUES (637,'University of Wisconsin-Milwaukee');
INSERT INTO College VALUES (638,'University of Wisconsin-Oshkosh');
INSERT INTO College VALUES (639,'University of Wisconsin-Parkside');
INSERT INTO College VALUES (640,'University of Wisconsin-River Falls');
INSERT INTO College VALUES (641,'University of Wisconsin-Stevens Point');
INSERT INTO College VALUES (642,'University of Wisconsin-Stout');
INSERT INTO College VALUES (643,'University of Wyoming');
INSERT INTO College VALUES (644,'Upper Iowa University');
INSERT INTO College VALUES (645,'Upsala College');
INSERT INTO College VALUES (646,'Utah State University');
INSERT INTO College VALUES (647,'Valdosta State University');
INSERT INTO College VALUES (648,'Valley City State University');
INSERT INTO College VALUES (649,'Valparaiso University');
INSERT INTO College VALUES (650,'Vanderbilt University');
INSERT INTO College VALUES (651,'Villanova University');
INSERT INTO College VALUES (652,'Virginia Commonwealth University');
INSERT INTO College VALUES (653,'Virginia Military Institute');
INSERT INTO College VALUES (654,'Virginia Tech');
INSERT INTO College VALUES (655,'Virginia State University');
INSERT INTO College VALUES (656,'Virginia Union University');
INSERT INTO College VALUES (657,'Voorhees College');
INSERT INTO College VALUES (658,'Wabash College');
INSERT INTO College VALUES (659,'Wagner College');
INSERT INTO College VALUES (660,'Wake Forest University');
INSERT INTO College VALUES (661,'Walsh University');
INSERT INTO College VALUES (662,'Washington &amp; Jefferson College');
INSERT INTO College VALUES (663,'Washington &amp; Lee University');
INSERT INTO College VALUES (664,'Washington State University');
INSERT INTO College VALUES (665,'Washington University in Saint Louis');
INSERT INTO College VALUES (666,'Wayne State University');
INSERT INTO College VALUES (667,'Weber State University');
INSERT INTO College VALUES (668,'West Liberty State College');
INSERT INTO College VALUES (669,'West Texas A&amp;M University');
INSERT INTO College VALUES (670,'West Virginia State University');
INSERT INTO College VALUES (671,'West Virginia University');
INSERT INTO College VALUES (672,'WVU Tech');
INSERT INTO College VALUES (673,'West Virginia Wesleyan College');
INSERT INTO College VALUES (674,'Western Carolina University');
INSERT INTO College VALUES (675,'Western Illinois University');
INSERT INTO College VALUES (676,'Western Kentucky University');
INSERT INTO College VALUES (677,'Western Michigan University');
INSERT INTO College VALUES (678,'Western New Mexico University');
INSERT INTO College VALUES (679,'Western Oregon University');
INSERT INTO College VALUES (680,'Westmar University');
INSERT INTO College VALUES (681,'Westminster College of Pennsylvania');
INSERT INTO College VALUES (682,'Westmont College');
INSERT INTO College VALUES (683,'Wheaton College');
INSERT INTO College VALUES (684,'Whittier College');
INSERT INTO College VALUES (685,'Whitworth');
INSERT INTO College VALUES (686,'Wichita State University');
INSERT INTO College VALUES (687,'Widener University');
INSERT INTO College VALUES (688,'Wilberforce University');
INSERT INTO College VALUES (689,'Wiley College');
INSERT INTO College VALUES (690,'Willamette University');
INSERT INTO College VALUES (691,'William Carey College');
INSERT INTO College VALUES (692,'William Paterson University');
INSERT INTO College VALUES (693,'Williams College');
INSERT INTO College VALUES (694,'Wilmington College');
INSERT INTO College VALUES (695,'Windham College');
INSERT INTO College VALUES (696,'Winona State University');
INSERT INTO College VALUES (697,'Winston-Salem State University');
INSERT INTO College VALUES (698,'Wittenberg University');
INSERT INTO College VALUES (699,'Wofford College');
INSERT INTO College VALUES (700,'Wright State University');
INSERT INTO College VALUES (701,'Xavier University');
INSERT INTO College VALUES (702,'Xavier University of Louisiana');
INSERT INTO College VALUES (703,'Yale University');
INSERT INTO College VALUES (704,'Yankton College');
INSERT INTO College VALUES (705,'Yeshiva University');
INSERT INTO College VALUES (706,'York College of Pennsylvania');
INSERT INTO College VALUES (707,'Youngstown State University');

INSERT INTO Team VALUES ('ATL','Atlanta Hawks (Stl/Mil/Tri)');
INSERT INTO Team VALUES ('STL','Atlanta Hawks (Stl/Mil/Tri)');
INSERT INTO Team VALUES ('MTH','Atlanta Hawks (Stl/Mil/Tri)');
INSERT INTO Team VALUES ('BOS','Boston Celtics');
INSERT INTO Team VALUES ('NJN','Brooklyn Nets (NJ/NY)');
INSERT INTO Team VALUES ('BRK','Brooklyn Nets (NJ/NY)');
INSERT INTO Team VALUES ('CHA','Charlotte Hornets');
INSERT INTO Team VALUES ('CHI','Chicago Bulls');
INSERT INTO Team VALUES ('CLE','Cleveland Cavaliers');
INSERT INTO Team VALUES ('DAL','Dallas Mavericks');
INSERT INTO Team VALUES ('DEN','Denver Nuggets');
INSERT INTO Team VALUES ('DET','Detroit Pistons (FTW)');
INSERT INTO Team VALUES ('FTW','Detroit Pistons (FTW)');
INSERT INTO Team VALUES ('GSW','Golden State Warriors (SF/Phi)');
INSERT INTO Team VALUES ('SFW','Golden State Warriors (SF/Phi)');
INSERT INTO Team VALUES ('PHW','Golden State Warriors (SF/Phi)');
INSERT INTO Team VALUES ('HOU','Houston Rockets (SD)');
INSERT INTO Team VALUES ('SDR','Houston Rockets (SD)');
INSERT INTO Team VALUES ('IND','Indiana Pacers');
INSERT INTO Team VALUES ('LAC','Los Angeles Clippers (SD/Buf)');
INSERT INTO Team VALUES ('SDC','Los Angeles Clippers (SD/Buf)');
INSERT INTO Team VALUES ('BUF','Los Angeles Clippers (SD/Buf)');
INSERT INTO Team VALUES ('LAL','Los Angeles Lakers (Min)');
INSERT INTO Team VALUES ('MNL','Los Angeles Lakers (Min)');
INSERT INTO Team VALUES ('MEM','Memphis Grizzlies (Van)');
INSERT INTO Team VALUES ('VAN','Memphis Grizzlies (Van)');
INSERT INTO Team VALUES ('MIA','Miami Heat');
INSERT INTO Team VALUES ('MIL','Milwaukee Bucks');
INSERT INTO Team VALUES ('MIN','Minnesota Timberwolves');
INSERT INTO Team VALUES ('NOH','New Orleans Pelicans');
INSERT INTO Team VALUES ('NYK','New York Knicks');
INSERT INTO Team VALUES ('OKC','Oklahoma City Thunder (Sea)');
INSERT INTO Team VALUES ('SEA','Oklahoma City Thunder (Sea)');
INSERT INTO Team VALUES ('ORL','Orlando Magic');
INSERT INTO Team VALUES ('PHI','Philadelphia 76ers (Syr)');
INSERT INTO Team VALUES ('SYR','Philadelphia 76ers (Syr)');
INSERT INTO Team VALUES ('PHO','Phoenix Suns');
INSERT INTO Team VALUES ('POR','Portland Trail Blazers');
INSERT INTO Team VALUES ('SAC','Sacramento Kings (KC/Cin/Roc)');
INSERT INTO Team VALUES ('CIN','Sacramento Kings (KC/Cin/Roc)');
INSERT INTO Team VALUES ('ROC','Sacramento Kings (KC/Cin/Roc)');
INSERT INTO Team VALUES ('KCK','Sacramento Kings (KC/Cin/Roc)');
INSERT INTO Team VALUES ('SAS','San Antonios Spurs (Tex/Dal)');
INSERT INTO Team VALUES ('TEX','San Antonios Spurs (Tex/Dal)');
INSERT INTO Team VALUES ('DLC','San Antonios Spurs (Tex/Dal)');
INSERT INTO Team VALUES ('TOR','Toronto Raptors');
INSERT INTO Team VALUES ('UTA','Utah Jazz (NO)');
INSERT INTO Team VALUES ('NOJ','Utah Jazz (NO)');
INSERT INTO Team VALUES ('WAS','Washington Wizards (Bal/Chi)');
INSERT INTO Team VALUES ('AND','Anderson Packers');
INSERT INTO Team VALUES ('BLB','Baltimore Bullets');
INSERT INTO Team VALUES ('CHS','Chicago Stags');
INSERT INTO Team VALUES ('CLR','Cleveland Rebels');
INSERT INTO Team VALUES ('DNN','Denver Nuggets');
INSERT INTO Team VALUES ('DTF','Detroit Falcons');
INSERT INTO Team VALUES ('INJ','Indianapolis Jets');
INSERT INTO Team VALUES ('INO','Indianapolis Olympians');
INSERT INTO Team VALUES ('KEN','Kentucky Colonels');
INSERT INTO Team VALUES ('MMS','Memphis Sounds (NO)');
INSERT INTO Team VALUES ('NOB','Memphis Sounds (NO)');
INSERT INTO Team VALUES ('PTC','Pittsburgh Condors (Min)');
INSERT INTO Team VALUES ('MNP','Pittsburgh Condors (Min)');
INSERT INTO Team VALUES ('PIT','Pittsburgh Ironmen');
INSERT INTO Team VALUES ('PRO','Providence Steamrollers');
INSERT INTO Team VALUES ('SDS','San Diego Sails');
INSERT INTO Team VALUES ('SHE','Sheboygan Redskins');
INSERT INTO Team VALUES ('SSL','Spirits of St. Louis (Car/Hou)');
INSERT INTO Team VALUES ('CAR','Spirits of St. Louis (Car/Hou)');
INSERT INTO Team VALUES ('HSM','Spirits of St. Louis (Car/Hou)');
INSERT INTO Team VALUES ('STB','St. Louis Bombers');
INSERT INTO Team VALUES ('FLO','The Floridians (Mia/Min)');
INSERT INTO Team VALUES ('MMF','The Floridians (Mia/Min)');
INSERT INTO Team VALUES ('MNM','The Floridians (Mia/Min)');
INSERT INTO Team VALUES ('TRH','Toronto Huskies');
INSERT INTO Team VALUES ('UTS','Utah Stars (LA/Ana)');
INSERT INTO Team VALUES ('LAS','Utah Stars (LA/Ana)');
INSERT INTO Team VALUES ('ANA','Utah Stars (LA/Ana)');
INSERT INTO Team VALUES ('VIR','Virginia Squires (Was/Oak)');
INSERT INTO Team VALUES ('WSA','Virginia Squires (Was/Oak)');
INSERT INTO Team VALUES ('OAK','Virginia Squires (Was/Oak)');
INSERT INTO Team VALUES ('WSC','Washington Capitols');
INSERT INTO Team VALUES ('WAT','Waterloo Hawks');
